language: php

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: TYPO3_VERSION=^7.6
    - php: 5.6
      env: TYPO3_VERSION=^7.6
    - php: 7.0
      env: TYPO3_VERSION=^7.6
    - php: 7.1
      env: TYPO3_VERSION=^7.6
    - php: 7.1
      env: TYPO3_VERSION=^8
    - php: 7.0
      env: TYPO3_VERSION=^8
    - php: 7.1
      env: TYPO3_VERSION=dev-master
    - php: 7.0
      env: TYPO3_VERSION=dev-master
    - php: nightly
      env: TYPO3_VERSION=dev-master
  allow_failures:
    - env: TYPO3_VERSION=dev-master
    - php: nightly

addons:
  apt:
    packages:
      - parallel

sudo: false

cache:
  directories:
  - "$HOME/.composer/cache"

before_install:
  - composer self-update
  - composer --version

install:
  - composer require --no-update "typo3/cms:$TYPO3_VERSION"
  - composer require --no-update "solarium/solarium"
  - if [[ "$TYPO3_VERSION" == "^8" ]]; then composer require --no-update "phpunit/phpunit:^5.0"; fi
  - composer install --prefer-dist
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
      echo;
      echo "Running php lint";
      find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - >
    echo;
    echo "Running unit tests";
    if [[ "$TYPO3_VERSION" == "dev-master" ]];
    then
      .Build/bin/phpunit --colors  -c .Build/vendor/typo3/cms/components/testing_framework/core/Build/UnitTests.xml Tests/Unit/
    else
      .Build/bin/phpunit --colors  -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml Tests/Unit/
    fi
